### ISSUE TITLE
Setting transfer size in the response header?

### ISSUE THREAD

**Issue by jkarlin** [WICG/transfer-size#11]
<iframe max-transfer-size="300kb" src="..."> is useful for iframes inserted by the first-party document, but doesn't help the first-party to control what frames inserted by third-party script can do. Which makes me wonder if we should have a response header, something like:

```http
Transfer-Size-Policy: default 100; self *; *.example.com 200
```

Where the default unit is KB.  WDYT? Paging @igrigorik @ojanvafai

**Comment by igrigorik** [comment]
*nod* .. Except, let's not invent more custom ABNF parsers and use JSON, like in Feature-Policy.

**Comment by jkarlin** [comment]
Sure, so more like

```http
Transfer-Size-Policy: {"default":"100KB", "self":"*", "*.example.com":"200KB"}
```
