### ISSUE TITLE
Document resource-types supported in transfersize

### ISSUE THREAD

**Issue by addyosmani** [WICG/transfer-size#17]
`transfersize` appears to support specifying a resource type (`style`, `video` etc) for providing budgets beyond just the frame level. It would be great to document what this list of resource types is. 

Is it a list? Are we just matching these transfer-sizes to tag-types? (e.g `<style>`, `<video>`, `<script>`?) Some clarification would be helpful here.

```
  <iframe id="foo" ontransferexceeded="onBigFrame(event)" transfersize="style:50, total:500" src="...">
  <iframe id="foo" ontransferexceeded="onBigFrame(event)" transfersize="video:10240" src="...">
```

**Comment by jkarlin** [comment]
It's from Fetch's [request destination](https://fetch.spec.whatwg.org/#concept-request-destination). I'll add it to the explainer.
