### ISSUE TITLE
Restrictions modified by browser config or platform flag?

### ISSUE THREAD

**Issue by tomByrer** [WICG/transfer-size#7]
This would be most helpful on low memory devices (eg phones, old computers, SoC), but less helpful on my Intel i5 20Gb laptop.  Could the restrictions be targeted to mobile?  Might be helpful if the browser auto-configs according the available memory buffer, but could also be a 'fingerprint' that can ID an user.

**Comment by jkarlin** [comment]
This API isn't meant to constrain memory usage. It's more about network bytes. And it could certainly be restricted to mobile cases, e.g., only use the size policy on iframes when the browser is on mobile (determined via netinfo api).

**Comment by jkarlin** [comment]
Other methods can be used to determine the platform. Once you have that, use transfer-size accordingly.
